blank_issues_enabled: false
contact_links:
  - name: â“ General Questions / Usage
    url: https://github.com/runefix-labs/runefix-core/discussions
    about: For questions or tips, please use Discussions instead of Issues.
